In [1]:
### MOOC at edX: Python for Data Science
# completed 11/4/2018

# this is an introductory course for learning
# it will start off with basic functions 
# dataset: recent-grads

In [6]:
# read and explore your data

#import pandas 
import pandas as pd
#use pandas to read in recent_grads_url
recent_grads = pd.read_csv("recent-grads.csv")
#print the shape
print(recent_grads.shape)

(173, 21)


In [8]:
# exploring your data

#print .dtypes
print(recent_grads.dtypes)
#output summary statistics
print(recent_grads.describe())
#exclude data of type object
print(recent_grads.describe(exclude=["object"]))

Rank                      int64
Major_code                int64
Major                    object
Total                   float64
Men                     float64
Women                   float64
Major_category           object
ShareWomen              float64
Sample_size               int64
Employed                  int64
Full_time                 int64
Part_time                 int64
Full_time_year_round      int64
Unemployed                int64
Unemployment_rate       float64
Median                    int64
P25th                     int64
P75th                     int64
College_jobs              int64
Non_college_jobs          int64
Low_wage_jobs             int64
dtype: object
             Rank   Major_code          Total            Men          Women  \
count  173.000000   173.000000     172.000000     172.000000     172.000000   
mean    87.000000  3879.815029   39370.081395   16723.406977   22646.674419   
std     50.084928  1687.753140   63483.491009   28122.433474   41057.330740  

In [14]:
# clean

#names of the columns we're searching for missing values 
columns = ['Median', 'P25th', 'P75th']
#take a look at the dtypes
print(recent_grads[columns].dtypes)
#find how missing values are represented
print(recent_grads["Median"].unique())
#replace missing values with NaN
#import numpy
import numpy as np
for column in columns:
    recent_grads.loc[recent_grads[column] == 'UN', column] = np.nan

Median    int64
P25th     int64
P75th     int64
dtype: object
[110000  75000  73000  70000  65000  62000  60000  58000  57100  57000
  56000  54000  53000  52000  51000  50000  48000  47000  46000  45000
  44700  44000  42000  41300  41000  40100  40000  39000  38400  38000
  37500  37400  37000  36400  36200  36000  35600  35000  34000  33500
  33400  33000  32500  32400  32200  32100  32000  31500  31000  30500
  30000  29000  28000  27500  27000  26000  25000  23400  22000]


In [17]:
# selecting data, convert to numpy array

#select sharewomen column
sw_col = recent_grads['ShareWomen']
#output first five rows
print(sw_col.head())

#use max to output maximum values
max_sw = max(recent_grads.ShareWomen)
#print column max
print(max_sw)

#output the row containing the maximum percentage of women
print(recent_grads[sw_col == max_sw])

#convert to numpy array
recent_grads_np = recent_grads[["Unemployed", "Low_wage_jobs"]].values

#print the type of recent_grads_np
print(type(recent_grads_np))

#calculate correlation matrix
print(np.corrcoef(recent_grads_np[:,0], recent_grads_np[:,1]))

0    0.120564
1    0.101852
2    0.153037
3    0.107313
4    0.341631
Name: ShareWomen, dtype: float64
0.968953683
     Rank  Major_code                      Major    Total     Men    Women  \
164   165        2307  EARLY CHILDHOOD EDUCATION  37589.0  1167.0  36422.0   

    Major_category  ShareWomen  Sample_size  Employed      ...        \
164      Education    0.968954          342     32551      ...         

     Part_time  Full_time_year_round  Unemployed  Unemployment_rate  Median  \
164       7001                 20748        1360           0.040105   28000   

     P25th  P75th  College_jobs  Non_college_jobs  Low_wage_jobs  
164  21000  35000         23515              7705           2868  

[1 rows x 21 columns]
<class 'numpy.ndarray'>
[[1.         0.95538815]
 [0.95538815 1.        ]]


In [18]:
# math operations:

#add
print(7+10) 
#subtract
print(5-5)
#multiply
print(3*5)
#divide
print(5/8)
#exponent
print(4**2)
#modulo
print(18%7)
# $100 investment for 7 years at 10% interest
print(100*1.1**7)

17
0
15
0.625
16
4
194.87171000000012


In [19]:
# variable types

desc = "compound interest"
print(type(desc))
#str type

#definition of savings and result
savings = 100
result = 100*1.10**7

#fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

#definition of pi_string
pi_string = "3.1415926"

#convert pi_string into float: pi_float
pi_float = float(pi_string)

#convert to string
print("I can add integers, like " + str(5) + " to strings.")
print("I said " + ("Hey " * 2) + "Hey!")

print(True + True)
print(True + False)

<class 'str'>
I started with $100 and now have $194.87171000000012. Awesome!
I can add integers, like 5 to strings.
I said Hey Hey Hey!
2
1


In [20]:
# lists

#create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
#print out second element from areas
print(areas[1])
#print out last element from areas
print(areas[-1])
#print out the area of the living room
print(areas[5])

#create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
#sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[-3]
#print the variable eat_sleep_area
print(eat_sleep_area)

#create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
#use slicing to create downstairs
downstairs = areas[0:6]
#use slicing to create upstairs
upstairs = areas[6:10]
upstairs = areas[-4:]
#print out downstairs and upstairs
print(downstairs)
print(upstairs)

#create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
#alternative slicing to create downstairs
downstairs = areas[:6]
#alternative slicing to create upstairs
upstairs = areas[-4:]

#create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
#correct the bathroom area
areas[-1] = 10.50 
#change "living room" to "chill zone"
areas[4] = "chill zone"

#create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]
#add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]
#add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

#delete list elements
del(areas[-4:-2])

#create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
#create areas_copy
areas_copy = list(areas)
#change areas_copy
areas_copy[0] = 5.0
#print areas
print(areas)

11.25
9.5
20.0
28.75
['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]
[11.25, 18.0, 20.0, 10.75, 9.5]


In [25]:
# functions and packaging

#create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True
#print out type of var1
print(type(var1))
#print out length of var1
print(len(var1))
#convert var2 to an integer: out2
out2 = int(var2)

#help!
help(max)
?max

#create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]
#paste together first and second: full
full = first + second
#sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)
#print out full_sorted
print(full_sorted)

#string to experiment with: room
room = "poolhouse"
#use upper() on room: room_up
room_up = room.upper()
#print out room and room_up
print(room)
print(room_up)
#print out the number of o's in room
print(room.count("o"))

#create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
#print out the index of the element 20.0
print(areas.index(20.0))
#print out how often 14.5 appears in areas
print(areas.count(14.5))

#create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

#use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)
#print out areas
print(areas)
#reverse the orders of the elements in areas
areas.reverse()
#print out areas
print(areas)

#definition of radius
r = 0.43
#import the math package
import math
#calculate C
C = round(2*math.pi*r,4)
#calculate A
A = math.pi*r**2
#build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

#definition of radius
r = 192500
#import radians function of math package
from math import radians
#travel distance of Moon if 12 degrees. Store in dist.
dist = r * radians(12)
#print out dist
print(dist)

#different ways of importing
from scipy.linalg import inv as my_inv
my_inv([[1,2], [3,4]])

<class 'list'>
4
Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.

[20.0, 18.0, 11.25, 10.75, 9.5]
poolhouse
POOLHOUSE
3
2
0
[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]
Circumference: 2.7018
Area: 0.5808804816487527
40317.10572106901


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [44]:
# numpy

#read csv
baseball_data = pd.read_csv("baseball.csv")
#create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
#import numpy and pandas
import numpy as np
#create a Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
#print out type of np_baseball
print(type(np_baseball))

#import numpy
import numpy as np

#create a Numpy array from height: np_height
np_height = np.array(baseball_data["Height"])

#print out np_height
print(np_height)
# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254
#print np_height_m
print(np_height_m)

#create array from height with correct units: np_height_m
np_height_m = np.array(baseball_data["Height"]) * 0.0254
#create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(baseball_data["Weight"]) * 0.453592
#calculate the BMI: bmi
bmi = np_weight_kg / (np_height_m ** 2)
#print out bmi
print(bmi)

#calculate the BMI: bmi
np_height_m = np.array(baseball_data["Height"]) * 0.0254
np_weight_kg = np.array(baseball_data["Weight"]) * 0.453592
bmi = np_weight_kg / np_height_m ** 2
#create the light array
light = bmi < 21
#print out light
print(light)
#print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

#store weight and height lists as numpy arrays
np_weight = np.array(baseball_data["Weight"])
np_height = np.array(baseball_data["Height"])
#print out the weight at index 50
print(np_weight[50])
#print out sub-array of np_height: index 100 up to and including index 110
print(np_height[100:111])

#create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]
#create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array(baseball_data)
#print out the type of np_baseball
print(type(np_baseball))
#print out the shape of np_baseball
print(np_baseball.shape)

#print out the 50th row of np_baseball
print(np_baseball[49,])
#select the entire second column of np_baseball: np_weight
np_weight = np_baseball[:,4]
#print out height of 124th player
print(np_baseball[123,0])

#create np_height from np_baseball
np_height = np_baseball[:,3]
#print out the mean of np_height
print(np.mean(np_height))
#print out the median of np_height
print(np.median(np_height))

#print mean height (first column)
avg = np.mean(np_baseball[:,3])
print("Average: " + str(avg))
#print median height. Replace 'None'
med = np.median(np_baseball[:,4])
print("Median: " + str(med))
#print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,3])
print("Standard Deviation: " + str(stddev))
#print out correlation between height and weight column. Replace 'None'
#corr = np.corrcoef(np_baseball[:,3], np_baseball[:,4])
#print("Correlation: " + str(corr))

#convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(baseball_data["Position"]) 
np_heights = np.array(baseball_data["Height"])
#heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']
#heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']
#print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))
#print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

<class 'numpy.ndarray'>
[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]
[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]
[False False False ... False False False]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]
200
[73 74 72 73 69 72 73 75 75 73 72]
<class 'numpy.ndarray'>
(1015, 7)
['Rob_Mackowiak' 'CWS' 'Outfielder' 70 195 30.69 'Outfielder']
Kason_Gabbard
73.6896551724138
74.0
Average: 73.6896551724138
Median: 200.0
Standard Deviation: 2.3127918810465395
Median height of goalkeepers: nan
Median height of other players: 74.0


C:\Users\Ankur\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\Ankur\Anaconda3\lib\site-packages\numpy\core\_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [ ]:
# plotting with matplotlib

import matplotlib.pyplot as plt
# Make a line plot: year on the x-axis, pop on the y-axis
plt.plot(year,pop)
plt.show()

#What is the first year in which there will be more than ten billion human beings on this planet?
#population[year.index(2030)], to get the population for 2030, for example.

#print the last item of gdp_cap and life_exp
print(gdp_cap[-1], life_exp[-1])
#make a line plot, gdp_cap on the x-axis, life_exp on the y-axis
plt.plot(gdp_cap, life_exp)
#display the plot
plt.show()

#change the line plot below to a scatter plot
plt.plot(gdp_cap, life_exp)
plt.scatter(gdp_cap, life_exp)
#put the x-axis on a logarithmic scale
plt.xscale("log")
#show plot
plt.show()

#import package
import matplotlib.pyplot as plt
#build Scatter plot
plt.scatter(pop, life_exp)
#show plot
plt.show()

#create histogram of life_exp data
plt.hist(life_exp) 
#display histogram
plt.show()

#build histogram with 5 bins
plt.hist(life_exp, bins=5)
#show and clean up plot
plt.show()
plt.clf()
#build histogram with 20 bins
plt.hist(life_exp, bins=20)
#show and clean up again
plt.show()
plt.clf()

Build a histogram (3): compare
#histogram of life_exp, 15 bins
plt.hist(life_exp, bins=15)
#show and clear plot
plt.show()
plt.clf()
#histogram of life_exp1950, 15 bins
plt.hist(life_exp1950, bins=15)
#show and clear plot again
plt.show()
plt.clf()

#Choose the right plot (1)
#You're a professor teaching Data Science with Python, and you want to visually assess if the grades on your exam follow a normal distribution. Which plot do you use?
#Histogram

#Choose the right plot (2)
#You're a professor in Data Analytics with Python, and you want to visually assess if longer answers on exam questions lead to higher grades. Which plot do you use?
#Scatter plot

#basic scatter plot, log scale
plt.scatter(gdp_cap, life_exp)
plt.xscale('log') 
#strings
xlab = 'GDP per Capita [in USD]'
ylab = 'Life Expectancy [in years]'
title = 'World Development in 2007'
#add axis labels
plt.xlabel(xlab)
plt.ylabel(ylab)
#add title
plt.title(title)
#after customizing, display the plot
plt.show()

#scatter plot
plt.scatter(gdp_cap, life_exp)
#previous customizations
plt.xscale('log') 
plt.xlabel('GDP per Capita [in USD]')
plt.ylabel('Life Expectancy [in years]')
plt.title('World Development in 2007')
#definition of tick_val and tick_lab
tick_val = [1000,10000,100000]
tick_lab = ['1k','10k','100k']
#adapt the ticks on the x-axis
plt.xticks(tick_val, tick_lab)
#after customizing, display the plot
plt.show()

#store pop as a numpy array: np_pop
np_pop = np.array(pop)
#double np_pop
np_pop=np_pop*2
#update: set s argument to np_pop
plt.scatter(gdp_cap, life_exp, s=np_pop)
#previous customizations
plt.xscale('log') 
plt.xlabel('GDP per Capita [in USD]')
plt.ylabel('Life Expectancy [in years]')
plt.title('World Development in 2007')
plt.xticks([1000, 10000, 100000],['1k', '10k', '100k'])
#display the plot
plt.show()

Colors
#specify c and alpha inside plt.scatter()
plt.scatter(x = gdp_cap, y = life_exp, s = np.array(pop) * 2)
#previous customizations
plt.xscale('log') 
plt.xlabel('GDP per Capita [in USD]')
plt.ylabel('Life Expectancy [in years]')
plt.title('World Development in 2007')
plt.xticks([1000,10000,100000], ['1k','10k','100k'])
#show the plot
plt.show()
dict = {
    'Asia':'red',
    'Europe':'green',
    'Africa':'blue',
    'Americas':'yellow',
    'Oceania':'black'
}

#scatter plot
plt.scatter(x = gdp_cap, y = life_exp, s = np.array(pop) * 2, c = col, alpha = 0.8)
#previous customizations
plt.xscale('log') 
plt.xlabel('GDP per Capita [in USD]')
plt.ylabel('Life Expectancy [in years]')
plt.title('World Development in 2007')
plt.xticks([1000,10000,100000], ['1k','10k','100k'])
#additional customizations
plt.text(1550, 71, 'India')
plt.text(5700, 80, 'China')
#add grid() call
plt.grid(True)
#show the plot
plt.show()

In [ ]:
# control flow and pandas

# Comparison of booleans
print(True == False)
# Comparison of integers
print(-5*15 != 75)
# Comparison of strings
print("pyscript" == "PyScript")
# Compare a boolean with an integer
print(True == 1)

# Comparison of integers
x = -3 * 6
print(x >= -10)  
# Comparison of strings
y = "test"
print("test" <= y)
# Comparison of booleans
print(True > False)

and, or, not (1)
# Define variables
my_kitchen = 18.0
your_kitchen = 14.0
# my_kitchen bigger than 10 and smaller than 18?
print(my_kitchen > 10 and my_kitchen < 18)
# my_kitchen smaller than 14 or bigger than 17?
print(my_kitchen < 14 or my_kitchen > 17)
# Double my_kitchen smaller than triple your_kitchen?
print(my_kitchen * 2 < your_kitchen * 3)

# and, or, not (2)
x = 8
y = 9
not(not(x < 3) and not(y > 14 or y > 10))
#False
area = 10.0
if(area < 9) :
    print("small")
elif(area < 12) :
    print("medium")
else :
    print("large")
#medium

if
# Define variables
room = "kit"
area = 14.0
# if statement for room
if room == "kit" :
    print("looking around in the kitchen.")
# if statement for area
if area > 15:
    print("big place!")

# Define variables
room = "kit"
area = 14.0
# if-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
else :
    print("looking around elsewhere.")
# if-else construct for area
if area > 15 :
    print("big place!")
else:
    print("pretty small.")

# Define variables
room = "bed"
area = 14.0
# if-elif-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
elif room == "bed":
    print("looking around in the bedroom.")
else :
    print("looking around elsewhere.")
# if-elif-else construct for area
if area > 15 :
    print("big place!")
elif area > 10: 
    print("medium size, nice!")
else :
    print("pretty small.")

# Import pandas as pd
import pandas as pd
# Import the cars.csv data: cars
cars = pd.read_csv("cars.csv")
# Print out cars
print(cars)

# Import pandas as pd
import pandas as pd
# Fix import by including index_col
cars = pd.read_csv('cars.csv', index_col=0)
# Print out cars
print(cars)

# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)
# Print out country column as Pandas Series
print(cars["country"])
# Print out country column as Pandas DataFrame
print(cars[["country"]])

# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)
# Print out observation for Japan
print(cars.loc['JAP'])
# Print out observations for Australia and Egypt
print(cars.loc[['AUS', 'EG']])

# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)
# Print out drives_right value of Morocco
print(cars.loc['MOR', 'drives_right'])
# Print sub-DataFrame
print(cars.loc[['RU', 'MOR'], ['country', 'drives_right']])